version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: curadoria
    networks:
      - pds

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - dev-db
    env_file:
      - .env
    networks:
      - pds

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    env_file:
      - .env
    networks:
      - pds

networks:
  pds:
